<a href="https://colab.research.google.com/github/BlackSwan96/index.html/blob/main/My01AppliedCode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd   # pandas library works with data frames in Python
url="https://raw.githubusercontent.com/leonkag/Statistics0/main/HELPrct.csv"
mydata = pd.read_csv(url)   # save as mydata file
print('Data Frame dimensions: ',mydata.shape)   #rows and # cols

mydata = mydata[['cesd','age','mcs','pcs','homeless','substance','sex']];
mydata   # NOTE that Python counts from row 0!!!

Data Frame dimensions:  (453, 31)

     cesd  age        mcs        pcs  homeless substance     sex
0      49   37  25.111990  58.413689    housed   cocaine    male
1      30   37  26.670307  36.036942  homeless   alcohol    male
2      39   26   6.762923  74.806328    housed    heroin    male
3      15   39  43.967880  61.931679    housed    heroin  female
4      39   32  21.675755  37.345585  homeless   cocaine    male
..    ...  ...        ...        ...       ...       ...     ...
448    28   33  41.943066  56.968681    housed    heroin    male
449    37   49  62.175503  57.253838    housed   alcohol    male
450    28   39  33.434536  40.045715  homeless    heroin  female
451    11   59  54.424816  53.732044  homeless   cocaine    male
452    35   45  30.212227  43.476074  homeless   alcohol    male

[453 rows x 7 columns]

In [ ]:
import pandas as pd
url="https://raw.githubusercontent.com/leonkag/Statistics0/main/CPS85.csv"
mydata = pd.read_csv(url)   # save as mydata file
print('Data Frame dimensions: ',mydata.shape)   # data shape #rows and # cols
mydata = mydata[['wage','educ','race','sex','south','married','exper','sector']];
mydata.head(10)

Data Frame dimensions:  (534, 12)

    wage  educ race sex south  married  exper    sector
0   9.00    10    W   M    NS  Married     27     const
1   5.50    12    W   M    NS  Married     20     sales
2   3.80    12    W   F    NS   Single      4     sales
3  10.50    12    W   F    NS  Married     29  clerical
4  15.00    12    W   M    NS  Married     40     const
5   9.00    16    W   F    NS  Married     27  clerical
6   9.57    12    W   F    NS  Married      5   service
7  15.00    14    W   M    NS   Single     22     sales
8  11.00     8    W   M    NS  Married     42     manuf
9   5.00    12    W   F    NS  Married     14     sales

In [ ]:
import pandas as pd
url="https://raw.githubusercontent.com/leonkag/Statistics0/main/MHEALTH.csv"
mydata = pd.read_csv(url)   # save as mydata file
print('Data Frame dimensions: ',mydata.shape)   # data shape #rows and # cols
mydata = mydata[['AGE','HT','WT','WAIST','PULSE','BMI']];
mydata.head(10)

In [ ]:
import pandas as pd;
import seaborn as sns  # seaborn is an high level Statistics graphics library

url="https://raw.githubusercontent.com/leonkag/Statistics0/main/HELPrct.csv"
mydata = pd.read_csv(url)   # save as mydata file
# mydata.head(10)
sns.scatterplot(data=mydata, x="mcs", y="cesd")

In [ ]:
url="https://raw.githubusercontent.com/leonkag/Statistics0/main/MHEALTH.csv"
mydata = pd.read_csv(url)   # save as mydata file
# mydata.head(10)
sns.scatterplot(data=mydata, x="WAIST", y="WT")

In [ ]:
sns.scatterplot(data=mydata, x="PULSE", y="WT")